version: "3.8"

services:
  GPT-SoVITS-CU126:
    image: sky1218/gpt-sovits:latest-cu126
    container_name: GPT-SoVITS-CU126
    ports:
      - "9871:9871"
      - "9872:9872"
      - "9873:9873"
      - "9874:9874"
      - "9880:9880"
    volumes:
      - .:/workspace/GPT-SoVITS
    environment:
      - is_half=true
    tty: true
    stdin_open: true
    shm_size: "16g"
    restart: unless-stopped
    runtime: nvidia

  GPT-SoVITS-CU128:
    image: sky1218/gpt-sovits:latest-cu128
    container_name: GPT-SoVITS-CU128
    ports:
      - "9871:9871"
      - "9872:9872"
      - "9873:9873"
      - "9874:9874"
      - "9880:9880"
    volumes:
      - .:/workspace/GPT-SoVITS
    environment:
      - is_half=true
    tty: true
    stdin_open: true
    shm_size: "16g"
    restart: unless-stopped
    runtime: nvidia